default_stages: [commit]
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.62.3
    hooks:
      - id: terraform_tfsec
        args:
          - >
            --args=--exclude-downloaded-modules
      # - id: terraform_fmt
      #   arg:
      #     - --args=--config=__GIT_WORKING_DIR__/modules/aws/
      # - id: terraform_docs
      #   args:
      #     - --hook-config=--path-to-file=__GIT_WORKING_DIR__/modules/aws/README.md        # Valid UNIX path. I.e. ../TFDOC.md or docs/README.md etc.
      #     - --hook-config=--add-to-existing-file=true     # Boolean. true or false
      #     - --hook-config=--create-file-if-not-exist=true # Boolean. true or false
